-- CREATING DATABASE
CREATE DATABASE IF NOT EXISTS CRUD_Node_MySQL;

--USING DATABASE
use CRUD_Node_MySQL;

--CREATING A TABLE
CREATE TABLE customers(
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL
);

--SHOW ALL TABLES
show TABLES;

--DESCRIBE TABLE
describe customers;